from selenium import webdriver
import time
browser = webdriver.Chrome("C:\SE\chromedriver.exe")
from selenium.webdriver.support.select import Select
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
time.sleep(2)
browser.maximize_window()
browser.get('http://139.162.35.76:8070/login')
time.sleep(2)
browser.find_element_by_name("email").send_keys("super@skylarksoft.com")
time.sleep(2)
browser.find_element_by_name("password").send_keys("Staging!Er$#P@2021")
time.sleep(2)
browser.find_element_by_name("login").click()
time.sleep(2)
browser.find_element_by_xpath("(//span[@class='nav-text'][contains(.,'Marketing')])[1]").click()
time.sleep(2)
browser.find_element_by_xpath("(//span[@class='nav-text'][contains(.,'Price Quotation')])[1]").click()
time.sleep(2)
browser.find_element_by_xpath("//a[contains(.,'New Entry')]").click()
time.sleep(2)
browser.find_element_by_xpath("//input[@id='revised_no']").send_keys("1001")
time.sleep(2)
browser.find_element_by_xpath("//input[@id='location']").send_keys("Mirpur,Dhaka")
time.sleep(2)
a1 = Select(browser.find_element_by_id("buyer_id"))
a1.select_by_index(4)
time.sleep(2)
a2 = Select(browser.find_element_by_id("product_department_id"))
a2.select_by_index(4)
time.sleep(2)
browser.find_element_by_xpath("//input[@id='style_name']").send_keys("sssss")
time.sleep(2)
browser.find_element_by_xpath("//input[contains(@id,'style_desc')]").send_keys("good quality")
time.sleep(2)
browser.find_element_by_xpath("//input[contains(@id,'offer_qty')]").send_keys("5000")
time.sleep(3)
a2 = Select(browser.find_element_by_id("season_id"))
a2.select_by_index(1)
time.sleep(2)
browser.find_element_by_xpath("//input[contains(@id,'grp')]").send_keys("large")
time.sleep(2)
a3 = Select(browser.find_element_by_id("style_uom"))
a3.select_by_index(1)
time.sleep(2)
a4 = Select(browser.find_element_by_id("costing_per"))
a4.select_by_index(2)
time.sleep(2)
a5 = Select(browser.find_element_by_id("ready_to_approve"))
a5.select_by_index(1)
time.sleep(2)
a6 = Select(browser.find_element_by_id("garment_item_val"))
a6.select_by_index(6)
time.sleep(2)
browser.find_element_by_xpath("(//input[@type='text'])[19]").send_keys("1")
time.sleep(2)
browser.find_element_by_xpath("//input[@name='smv_val']").send_keys("6")
time.sleep(2)
browser.find_element_by_xpath("(//i[@class='fa fa-plus'])[2]").click()
time.sleep(2)
browser.find_element_by_xpath("(//button[@type='submit'])[1]").click()
time.sleep(4)
browser.find_element_by_xpath("//button[contains(.,'Costing Section')]").click()
time.sleep(3)
a = browser.find_element_by_xpath("//input[@name='fab_cost']")
action = ActionChains(browser)
action.double_click(a).perform()
time.sleep(2)
b1 = Select(browser.find_element_by_id("body_part_id"))
b1.select_by_index(2)
time.sleep(2)
browser.find_element_by_xpath("//input[@id='body_part_type']").send_keys("top")
time.sleep(2)
b2 = Select(browser.find_element_by_id("color_type_id"))
b2.select_by_index("1")
time.sleep(2)
b3 = Select(browser.find_element_by_id("fabric_composition_id"))
b3.select_by_index(2)
time.sleep(3)
browser.find_element_by_xpath("//input[contains(@id,'code')]").send_keys("123456")
time.sleep(2)
b4 = Select(browser.find_element_by_id("supplier_id"))
b4.select_by_index(1)
time.sleep(3)
browser.find_element_by_xpath("//input[contains(@id,'gsm')]").send_keys("160")
time.sleep(3)
b5 = Select(browser.find_element_by_id("uom"))
b5.select_by_index(1)
time.sleep(4)
b = browser.find_element_by_xpath("//input[contains(@id,'cons')]")
action = ActionChains(browser)
action.double_click(b).perform()
time.sleep(3)
browser.find_element_by_xpath("//input[@id='gmts_size']").send_keys("small")
time.sleep(2)
browser.find_element_by_xpath("//input[@id='dia']").send_keys("72")
time.sleep(2)
browser.find_element_by_xpath("//input[@id='cons']").send_keys("2.34")
time.sleep(3)
browser.find_element_by_xpath("//input[contains(@id,'process_loss')]").send_keys("15")
time.sleep(3)
browser.find_element_by_xpath("(//input[@id='rate'])[2]").send_keys(".435")
time.sleep(3)
browser.find_element_by_xpath("(//button[@type='button'])[5]").click()
time.sleep(3)
browser.find_element_by_xpath("(//button[@type='button'])[4]").click()
time.sleep(15)
browser.find_element_by_xpath("(//button[contains(@type,'button')])[3]").click()
time.sleep(3)
browser.find_element_by_xpath("//span[@id='select2-body_part_id-container']").click()
time.sleep(2)
browser.find_element_by_xpath("(//li[@role='option'])[2]").click()
time.sleep(2)
browser.find_element_by_xpath("//span[@id='select2-uom-container']").click()
time.sleep(3)
browser.find_element_by_xpath("(//li[@role='option'])[5]").click()
time.sleep(5)
browser.find_element_by_xpath("(//button[@class='btn btn-xs btn-success'])[3]").click()
time.sleep(5)
browser.find_element_by_xpath("//button[@id='saveAllData']").click()
time.sleep(5)