from selenium import webdriver
import time
browser = webdriver.Chrome("C:\SE\chromedriver.exe")
from selenium.webdriver.support.select import Select
time.sleep(2)
browser.maximize_window()
browser.get('http://139.162.35.76:8070/login')
time.sleep(5)
browser.find_element_by_name("email").send_keys("super@skylarksoft.com")
time.sleep(5)
browser.find_element_by_name("password").send_keys("Staging!Er$#P@2021")
time.sleep(5)
browser.find_element_by_name("login").click()
time.sleep(2)
browser.find_element_by_xpath("(//span[@class='nav-text'][contains(.,'Marketing')])[1]").click()
time.sleep(2)
browser.find_element_by_xpath("//span[@class='nav-text'][contains(.,'Sales Target Determination')]").click()
time.sleep(2)
browser.find_element_by_xpath("//a[@href='http://139.162.35.76:8070/sales-target-determination/create']").click()
time.sleep(2)
a1 = Select(browser.find_element_by_xpath("//select[contains(@id,'buyer_id')]"))
a1.select_by_index(2)
time.sleep(2)
a2 = Select(browser.find_element_by_xpath("//select[contains(@id,'buying_agent_id')]"))
a2.select_by_index(2)
time.sleep(2)
a3 = Select(browser.find_element_by_xpath("//select[contains(@id,'team_leader_id')]"))
a3.select_by_index(3)
time.sleep(2)
a4 = Select(browser.find_element_by_xpath("//select[contains(@id,'month')]"))
a4.select_by_index(2)
time.sleep(2)
a5 = Select(browser.find_element_by_xpath("//select[contains(@id,'year')]"))
a5.select_by_index(3)
time.sleep(2)
browser.execute_script("window.scrollTo(0,document.body.scrollHeight)")
time.sleep(2)
browser.find_element_by_xpath("//button[contains(.,'Create')]").click()
time.sleep(2)


