from selenium import webdriver
import time
browser = webdriver.Chrome("C:\SE\chromedriver.exe")
from selenium.webdriver.support.select import Select
from selenium.webdriver.common.action_chains import ActionChains
time.sleep(2)
browser.maximize_window()
browser.get('http://139.162.35.76:8070/login')
time.sleep(2)
browser.find_element_by_name("email").send_keys("super@skylarksoft.com")
time.sleep(2)
browser.find_element_by_name("password").send_keys("Staging!Er$#P@2021")
time.sleep(2)
browser.find_element_by_name("login").click()
time.sleep(2)
browser.find_element_by_xpath("//span[@class='nav-text'][contains(.,'General Settings')]").click()
time.sleep(2)
browser.find_element_by_xpath("(//span[contains(.,'Users')])[2]").click()
time.sleep(2)
browser.find_element_by_xpath("//a[@href='http://139.162.35.76:8070/users/create']").click()
time.sleep(2)
browser.find_element_by_xpath("//input[@id='first_name']").send_keys("Nipun")
time.sleep(2)
browser.find_element_by_xpath("//input[@id='last_name']").send_keys("Nipu")
time.sleep(2)
browser.find_element_by_xpath("//input[contains(@id,'email')]").send_keys("nipun@gmail.com")
time.sleep(2)
browser.find_element_by_xpath("//input[contains(@id,'phone_no')]").send_keys("01222222")
time.sleep(2)
browser.find_element_by_xpath("//input[contains(@id,'designation')]").send_keys("Engineer")
time.sleep(2)
a1 = Select(browser.find_element_by_id("department"))
a1.select_by_index(1)
a2 = Select(browser.find_element_by_id("factory"))
a2.select_by_index(1)
a3 = Select(browser.find_element_by_id("role"))
a3.select_by_index(3)
browser.find_element_by_xpath("//input[@id='password']").send_keys("123456")
time.sleep(2)
browser.find_element_by_xpath("//input[@id='confirm_password']").send_keys("123456")
time.sleep(2)
browser.find_element_by_xpath("//textarea[@id='address']").send_keys("Mirpur")
time.sleep(2)
browser.find_element_by_xpath("//button[contains(.,'Create')]").click()
time.sleep(2)