from selenium import webdriver
import time
browser = webdriver.Chrome("C:\SE\chromedriver.exe")
from selenium.webdriver.support.select import Select
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
time.sleep(2)
browser.maximize_window()
browser.get('http://139.162.35.76:8070/login')
time.sleep(2)
browser.find_element_by_name("email").send_keys("super@skylarksoft.com")
time.sleep(2)
browser.find_element_by_name("password").send_keys("Staging!Er$#P@2021")
time.sleep(2)
browser.find_element_by_name("login").click()
time.sleep(2)
browser.find_element_by_xpath("(//span[contains(.,'General Settings')])[1]").click()
time.sleep(2)
browser.find_element_by_xpath("(//span[contains(.,'Factories')])[1]").click()
time.sleep(2)
browser.find_element_by_xpath("//a[contains(.,'New Factory')]").click()
time.sleep(2)
browser.find_element_by_xpath("//input[@name='group_name']").send_keys("Staging")
time.sleep(2)
browser.find_element_by_xpath("//input[@name='factory_name']").send_keys("Skylark Soft")
time.sleep(2)
browser.find_element_by_xpath("//input[@name='factory_short_name']").send_keys("SLS-1")
time.sleep(2)
browser.find_element_by_xpath("//textarea[@name='factory_address']").send_keys("Pallabi,Mirpur.Dhaka")
time.sleep(2)
browser.execute_script("window.scrollTo(0,document.body.scrollHeight)")
time.sleep(2)
browser.find_element_by_xpath("//button[contains(.,'Create')]").click()
time.sleep(2)