from selenium import webdriver
import time
browser = webdriver.Chrome("C:\SE\chromedriver.exe")
from selenium.webdriver.support.select import Select
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
time.sleep(2)
browser.maximize_window()
browser.get('http://139.162.35.76:8070/login')
time.sleep(2)
browser.find_element_by_name("email").send_keys("super@skylarksoft.com")
time.sleep(2)
browser.find_element_by_name("password").send_keys("Staging!Er$#P@2021")
time.sleep(2)
browser.find_element_by_name("login").click()
time.sleep(2)
browser.find_element_by_xpath("(//span[contains(.,'General Settings')])[1]").click()
time.sleep(2)
browser.find_element_by_xpath("//span[contains(.,'Menus')]").click()
time.sleep(2)
browser.find_element_by_xpath("//a[@href='http://139.162.35.76:8070/menus/create']").click()
time.sleep(2)
browser.find_element_by_xpath("//input[@id='menu_name']").send_keys("Trims Store")
time.sleep(2)
browser.find_element_by_xpath("//input[@id='menu_url']").send_keys("#")
time.sleep(2)
a1 = Select(browser.find_element_by_id("module"))
a1.select_by_index(43)
time.sleep(2)
browser.find_element_by_xpath("//select[@id='left_menu']").click()
time.sleep(2)
a2 = Select(browser.find_element_by_id("left_menu"))
a2.select_by_index(1)
time.sleep(2)
browser.find_element_by_xpath("//input[@id='sort']").send_keys("1")
time.sleep(2)
browser.find_element_by_xpath("//button[contains(.,'Create')]").click()
time.sleep(2)