from selenium import webdriver
import time
browser = webdriver.Chrome("C:\SE\chromedriver.exe")
from selenium.webdriver.support.select import Select
from selenium.webdriver.common.action_chains import ActionChains
time.sleep(2)
browser.maximize_window()
browser.get('http://139.162.35.76:8070/login')
time.sleep(2)
browser.find_element_by_name("email").send_keys("super@skylarksoft.com")
time.sleep(2)
browser.find_element_by_name("password").send_keys("Staging!Er$#P@2021")
time.sleep(2)
browser.find_element_by_name("login").click()
time.sleep(2)
browser.find_element_by_xpath("(//span[contains(.,'Merchandising')])[1]").click()
time.sleep(2)
browser.find_element_by_xpath("//span[contains(.,'Order/Style Tracking')]").click()
time.sleep(2)
browser.find_element_by_xpath("//span[contains(.,'Order/Style Entry')]").click()
time.sleep(2)
browser.find_element_by_xpath("//a[@href='http://139.162.35.76:8070/orders/create']").click()
time.sleep(4)
browser.find_element_by_xpath("(//span[contains(@id,'select2--container')])[2]").click()
time.sleep(5)
browser.find_element_by_xpath("//li[@id='select2--result-s7a7-4']").click()
time.sleep(4)
browser.find_element_by_xpath("//input[contains(@placeholder,'%@<>+,./ Not Allowed]')]").click()
time.sleep(2)
browser.find_element_by_xpath("//input[contains(@placeholder,'%@<>+,./ Not Allowed]')]").send_keys("xvr")
time.sleep(2)
a = browser.find_element_by_xpath("//input[@placeholder='SMV']")
action = ActionChains(browser)
action.double_click(a).perform()
time.sleep(2)
browser.find_element_by_xpath("(//span[contains(@id,'select2--container')])[14]").click()
time.sleep(2)
browser.find_element_by_xpath("(//li[contains(.,'POLO')])[1]").click()
time.sleep(2)
browser.find_element_by_xpath("(//input[@type='number'])[3]").click()
time.sleep(2)
browser.find_element_by_xpath("//em[@class='fa fa-plus btn btn-xs btn-success']").click()
time.sleep(2)
browser.find_element_by_xpath("//button[contains(.,'Save & Close')]").click()
time.sleep(2)
browser.find_element_by_xpath("//button[contains(.,'Create')]").click()
time.sleep(5)
browser.find_element_by_xpath("//button[contains(.,'Save & New PO')]").click()
time.sleep(2)
